# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-new-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-new
  template:
    metadata:
      labels:
        app: backend-new
    spec:
      containers:
        - name: backend-new
          image: art-web-backend:latest
          imagePullPolicy: Never
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: psql-config
                  key: host
            - name: HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: psql-config
                  key: name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: psql-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-postgres-postgresql
                  key: pastgres-password
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-new-service
spec:
  selector:
    app: backend-new
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
